#include "OGUICheckBox.h"

namespace OpenCVGUI {




void OGUICheckBox::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008ED begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008ED end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

OGUICheckBox::OGUICheckBox()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000935 begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000935 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace OpenCVGUI */
