#include "OGUISlider.h"

namespace OpenCVGUI {




void OGUISlider::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008F9 begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008F9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

OGUISlider::OGUISlider()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:000000000000092B begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:000000000000092B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace OpenCVGUI */
