#include "OGUITextInput.h"

namespace OpenCVGUI {




void OGUITextInput::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008EA begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008EA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

OGUITextInput::OGUITextInput()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000933 begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000933 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace OpenCVGUI */
