#include "OGUIFormArea.h"

namespace OpenCVGUI {




void OGUIFormArea::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008DA begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008DA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

OGUIFormArea::OGUIFormArea(OGUIWindow* window): OGUIArea(window)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000927 begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000927 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace OpenCVGUI */
