#include "OGUIWidget.h"

namespace OpenCVGUI {




void OGUIWidget::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008E2 begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008E2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace OpenCVGUI */
