#include "OGUITitle.h"

namespace OpenCVGUI {




void OGUITitle::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008E6 begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008E6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

OGUITitle::OGUITitle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000931 begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000931 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace OpenCVGUI */
