#include "OGUIButton.h"

namespace OpenCVGUI {




void OGUIButton::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008E4 begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008E4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

OGUIButton::OGUIButton()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:000000000000092F begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:000000000000092F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace OpenCVGUI */
