#include "OGUI3D.h"

namespace OpenCVGUI {




void OGUI3D::draw()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008DC begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:00000000000008DC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

OGUI3D::OGUI3D(OGUIWindow* window): OGUIArea(window)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000929 begin
{
}
// section 127-0-1-1--432a1702:1559adfe96b:-8000:0000000000000929 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace OpenCVGUI */
